/**
 * Production default voxel race characters — built from Avatar Edit's
 * 6-race catalog (`defaultConfig`) plus Explorer box-body looks.
 *
 * These are the fleet SSOT for "pick a race and play" in voxel games
 * (Animator, VoxGrudge openworld, GRUDOX). Not grudge6 Toon RTS kits and
 * not free-rpg TPose GLBs — the modular cube avatar system only.
 *
 * Ship path: `public/avatar/races/defaults.json` (written by
 * `scripts/export-voxel-race-defaults.mjs`). Games may import this module
 * or fetch the JSON.
 */
import {
  RACES,
  defaultConfig,
  encodeConfig,
  raceDef,
  skinToneOf,
  type AvatarConfig,
  type RaceId,
} from "./catalog";

/** CSS hex for Explorer {@link CharacterLook} fields. */
function cssHex(n: number): string {
  return "#" + (n >>> 0).toString(16).padStart(6, "0");
}

/** Body kit that matches a race head so the full voxel reads as one character. */
export interface VoxelRaceBodyLook {
  skin: string;
  shirt: string;
  pants: string;
  hat: "none" | "cap" | "horns" | "ledMask";
  hatColor: string;
  cape: boolean;
  capeColor: string;
  /** Always true for race defaults — head comes from AvatarConfig. */
  avatarHead: true;
}

export interface VoxelRaceDefault {
  /** Race id — same as AvatarConfig.race. */
  id: RaceId;
  /** Fleet avatar id for saves / handoffs (`avatar-human`, …). */
  avatarId: string;
  label: string;
  blurb: string;
  /** Full Avatar Edit build (modular cube head). */
  config: AvatarConfig;
  /** Share code (AV1.…). */
  code: string;
  /** Explorer box-body colours (SI voxel rig). */
  look: VoxelRaceBodyLook;
  /** Target height in metres (1 unit = 1 m). */
  heightM: number;
  /** Soft class hint for loadouts / openworld pickers. */
  classHint: "melee" | "ranged" | "magic" | "rogue";
  /** Relative portrait path under public/ (generated by export script). */
  portraitPath: string;
  /** Relative face PNG path (16×16 nearest scale). */
  facePath: string;
  /** Packed skin tone 0xRRGGBB. */
  skinTone: number;
  /** Kind tag so consumers never confuse with grudge6. */
  kind: "voxel-avatar-race";
  renderPipeline: "voxel";
}

/** Per-race body kit + gameplay defaults (head always from catalog). */
const RACE_BODY: Record<
  RaceId,
  Omit<VoxelRaceDefault, "id" | "avatarId" | "label" | "blurb" | "config" | "code" | "skinTone" | "portraitPath" | "facePath" | "kind" | "renderPipeline" | "look"> & {
    look: Omit<VoxelRaceBodyLook, "skin" | "avatarHead">;
  }
> = {
  human: {
    heightM: 1.8,
    classHint: "melee",
    look: {
      shirt: "#c0392b",
      pants: "#2e3440",
      hat: "none",
      hatColor: "#b03030",
      cape: false,
      capeColor: "#1a1e2b",
    },
  },
  barbarian: {
    heightM: 1.95,
    classHint: "melee",
    look: {
      shirt: "#6b5a2f",
      pants: "#3a2c1c",
      hat: "none",
      hatColor: "#6b5a2f",
      cape: true,
      capeColor: "#4a3520",
    },
  },
  orc: {
    heightM: 2.0,
    classHint: "melee",
    look: {
      shirt: "#2b2e35",
      pants: "#3a4030",
      hat: "none",
      hatColor: "#2b2e35",
      cape: false,
      capeColor: "#1a1e2b",
    },
  },
  undead: {
    heightM: 1.8,
    classHint: "magic",
    look: {
      shirt: "#4a5048",
      pants: "#2a2e2c",
      hat: "none",
      hatColor: "#8d9296",
      cape: true,
      capeColor: "#2b2e35",
    },
  },
  dwarf: {
    heightM: 1.5,
    classHint: "melee",
    look: {
      shirt: "#8a2f2f",
      pants: "#3a3428",
      hat: "none",
      hatColor: "#c2a23b",
      cape: false,
      capeColor: "#1a1e2b",
    },
  },
  elf: {
    heightM: 1.85,
    classHint: "ranged",
    look: {
      shirt: "#3f6d4e",
      pants: "#2a3540",
      hat: "none",
      hatColor: "#c2a23b",
      cape: false,
      capeColor: "#1a1e2b",
    },
  },
};

/** Build one production race default from the Avatar catalog. */
export function buildRaceDefault(race: RaceId): VoxelRaceDefault {
  const def = raceDef(race);
  const config = defaultConfig(race);
  const body = RACE_BODY[race];
  const skinTone = skinToneOf(config);
  return {
    id: race,
    avatarId: `avatar-${race}`,
    label: def.label,
    blurb: def.blurb,
    config,
    code: encodeConfig(config),
    look: {
      skin: cssHex(skinTone),
      shirt: body.look.shirt,
      pants: body.look.pants,
      hat: body.look.hat,
      hatColor: body.look.hatColor,
      cape: body.look.cape,
      capeColor: body.look.capeColor,
      avatarHead: true,
    },
    heightM: body.heightM,
    classHint: body.classHint,
    portraitPath: `avatar/races/${race}-portrait.png`,
    facePath: `avatar/races/${race}-face.png`,
    skinTone,
    kind: "voxel-avatar-race",
    renderPipeline: "voxel",
  };
}

/** All six production race defaults (stable order matches {@link RACES}). */
export function listRaceDefaults(): VoxelRaceDefault[] {
  return RACES.map((r) => buildRaceDefault(r.id));
}

export function raceDefault(id: RaceId): VoxelRaceDefault {
  return buildRaceDefault(id);
}

/** Fleet manifest shape written to `public/avatar/races/defaults.json`. */
export interface VoxelRaceDefaultsManifest {
  version: 1;
  kind: "voxel-avatar-race-defaults";
  source: "avatar-edit-catalog";
  note: string;
  races: VoxelRaceDefault[];
}

export function buildRaceDefaultsManifest(): VoxelRaceDefaultsManifest {
  return {
    version: 1,
    kind: "voxel-avatar-race-defaults",
    source: "avatar-edit-catalog",
    note:
      "Default playable voxel race characters from Avatar Edit (6 modular cube races). " +
      "Use config + look with Explorer/VoxelCharacter; not grudge6, not free-rpg TPose.",
    races: listRaceDefaults(),
  };
}

/** localStorage key for the published 6-race package (per-browser fleet seed). */
export const RACE_DEFAULTS_STORE_KEY = "avatarEdit:raceDefaults:v1";

/** Persist all six race defaults into localStorage for voxel games on this origin. */
export function saveRaceDefaultsToStorage(races: VoxelRaceDefault[] = listRaceDefaults()): void {
  try {
    localStorage.setItem(
      RACE_DEFAULTS_STORE_KEY,
      JSON.stringify({ version: 1, races, savedAt: Date.now() }),
    );
  } catch {
    /* storage blocked */
  }
}

/** Load published race defaults from localStorage; null when missing. */
export function loadRaceDefaultsFromStorage(): VoxelRaceDefault[] | null {
  try {
    const raw = localStorage.getItem(RACE_DEFAULTS_STORE_KEY);
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { races?: VoxelRaceDefault[] };
    if (!Array.isArray(parsed.races) || parsed.races.length === 0) return null;
    return parsed.races;
  } catch {
    return null;
  }
}

/**
 * Ensure the player has a saved head: use existing save, else seed the race
 * default (human when race unknown). Returns the config that should be worn.
 */
export function ensureRaceHeadConfig(
  race: RaceId = "human",
  loadSaved: () => AvatarConfig | null,
  saveSaved: (cfg: AvatarConfig) => void,
): AvatarConfig {
  const existing = loadSaved();
  if (existing) return existing;
  const cfg = defaultConfig(race);
  saveSaved(cfg);
  return cfg;
}
