// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/equipment-lab/EquipmentLab.tsx": () => import("../components/mockups/equipment-lab/EquipmentLab.tsx"),
  "./components/mockups/fx-asset-lab/BloodFX.tsx": () => import("../components/mockups/fx-asset-lab/BloodFX.tsx"),
  "./components/mockups/fx-asset-lab/Crosshairs.tsx": () => import("../components/mockups/fx-asset-lab/Crosshairs.tsx"),
  "./components/mockups/fx-asset-lab/GameReadyHUD.tsx": () => import("../components/mockups/fx-asset-lab/GameReadyHUD.tsx"),
  "./components/mockups/fx-asset-lab/HitsparkFX.tsx": () => import("../components/mockups/fx-asset-lab/HitsparkFX.tsx"),
  "./components/mockups/fx-asset-lab/PixelUI.tsx": () => import("../components/mockups/fx-asset-lab/PixelUI.tsx"),
  "./components/mockups/ledmask-redesign/CleanConsole.tsx": () => import("../components/mockups/ledmask-redesign/CleanConsole.tsx"),
  "./components/mockups/ledmask-redesign/Current.tsx": () => import("../components/mockups/ledmask-redesign/Current.tsx"),
  "./components/mockups/ledmask-redesign/FriendlyStudio.tsx": () => import("../components/mockups/ledmask-redesign/FriendlyStudio.tsx"),
  "./components/mockups/ledmask-redesign/LiveMaskStage.tsx": () => import("../components/mockups/ledmask-redesign/LiveMaskStage.tsx")
};
